name: Build Linux

on:
  workflow_dispatch:
  push:
    branches: [dev]
    tags: ['v*']
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/linux.yml'
      - 'snap/**'
      - 'Telegram/build/**'
      - '!Telegram/build/docker/centos_env/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/linux.yml'
      - 'snap/**'
      - 'Telegram/build/**'
      - '!Telegram/build/docker/centos_env/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    name: Rocky Linux 8
    runs-on: ubuntu-latest

    strategy:
      matrix:
        defines:
          - ""

    env:
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      IMAGE_TAG: ghcr.io/telegramdesktop/tdesktop/centos_env:latest

    steps:
      - name: Clone.
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: First set up.
        run: |
          docker pull $IMAGE_TAG

      - name: Restore Telegram Desktop cache.
        id: cache-tdesktop
        if: env.ONLY_CACHE == 'false'
        uses: actions/cache/restore@v6
        with:
          path: ${{ runner.temp }}/.tdesktop-cache
          key: ${{ runner.OS }}-tdesktop-${{ matrix.defines || 'null' }}-${{ github.run_id }}
          restore-keys: ${{ runner.OS }}-tdesktop-${{ matrix.defines || 'null' }}-

      - name: Telegram Desktop build.
        if: env.ONLY_CACHE == 'false'
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=AyuGram ${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=AyuGram" >> $GITHUB_ENV
          fi

          mkdir -p ${{ runner.temp }}/.tdesktop-cache

          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          -v ${{ runner.temp }}/.tdesktop-cache:/var/cache/ccache \
          -e CONFIG=Debug \
          -e CCACHE_MAXSIZE=4G \
          -e CCACHE_SLOPPINESS=pch_defines,time_macros \
          $IMAGE_TAG \
          env -u CCACHE_DISABLE /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Debug \
          -D CMAKE_C_FLAGS_DEBUG="-O0 -fpch-preprocess" \
          -D CMAKE_CXX_FLAGS_DEBUG="-O0 -fpch-preprocess" \
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON \
          -D TDESKTOP_API_TEST=ON \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF \
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF \
          $DEFINE

      - name: Save Telegram Desktop cache.
        if: >
          always()
            && steps.cache-tdesktop.outputs.cache-hit != 'true'
            && env.ONLY_CACHE == 'false'
        uses: actions/cache/save@v6
        with:
          path: ${{ runner.temp }}/.tdesktop-cache
          key: ${{ steps.cache-tdesktop.outputs.cache-primary-key }}

      - name: Check.
        if: env.ONLY_CACHE == 'false'
        run: |
          filePath="out/Debug/AyuGram"
          if test -f "$filePath"; then
            echo "Build successfully done! :)"

            size=$(stat -c %s "$filePath")
            echo "File size of ${filePath}: ${size} Bytes."
          else
            echo "Build error, output file does not exist."
            exit 1
          fi

      - name: Move artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          cd out/Debug
          mkdir artifact
          mv {AyuGram,Updater} artifact/
      - uses: actions/upload-artifact@v7
        if: env.UPLOAD_ARTIFACT == 'true'
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: out/Debug/artifact/
